### ISSUE TITLE
Support for chat "tools" and "tool_results"

### ISSUE THREAD

**Issue by tomsanbear** [cohere-ai/cohere-typescript#142]
Is there an upcoming release that will include support for the "tools" parameter as documented here: https://docs.cohere.com/docs/tool-use

**Comment by billytrend-cohere** [comment]
Hey @tomsanbear thanks for getting in touch! we released 7.8.0 last night which should include everything tool use! Please see the following code sample. Feel free to reopen issue if you find any fields are missing that you were expecting.

https://github.com/cohere-ai/cohere-typescript/blob/f42c8768fb57107e776d2ed7ecaa405b87e34961/src/test/tests.test.ts#L158-L234

**Comment by ystoneman** [comment]
@billytrend-cohere great to see the tool use supported! I think it would be useful to show this with at least one additional line of code, in the example on https://www.npmjs.com/package/cohere-ai. Because I had to dig into closed issues and find this thread to confirm that this capability was available. Thank you!!
